spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule
    username: root
    password: 960qq2MT@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
